server:
  port: 8080

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/wikicars
    username: root
    password: rootpassword
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect

  flyway:
    enabled: true
    locations: classpath:db/migration